restricted-commands: # Commands requiring verification
  - stop

timezone: "Asia/Tehran" # Set your desired timezone, e.g., "America/New_York", "UTC", etc.

# Verification settings
verification:
  session-duration: 600    # Time (in seconds) after verification during which commands are allowed (e.g., 600 = 10 mins).
  code-length: 6           # Length of the generated codes (e.g., 6 = "ABC123").
  code-expiry: 200         # Expiration time (in seconds) for newly generated codes (e.g., 600 = 10 mins).

# Logs
logging:
  enabled: true            # Enable logging of code generation and usage.

backup-key: "DONOTSHARE" # Backup key for urgent use.